### ISSUE TITLE
30303/udp is not an port number

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_ADMIN#128]
Got an error when installing the Kovan package that indicated port 30303 was not opened.
```
Error: command -r : 30303/udp is not an port number

    at shellExecSync (/usr/src/app/src/modules/docker/shell.js:34:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

kwargs = {
  "action": "open",
  "ports": [
    "30303",
    "30303/udp",
    "30303",
    "30303/udp",
    "30303",
    "30303/udp"
  ],
  "logId": "6356c4c8-bf75-45e4-9f1c-d6e8f1ee6953"
}
```

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/d5d16e517440e5b38df506018e69583eb70a2fb7
