### ISSUE TITLE
Prysm Onyx Validator

### ISSUE THREAD

**Issue by Renaud-V** [dappnode/DNP_ADMIN#444]
*Before filing a new issue, please **provide the following information**.*

## Core DAppNode Packages versions
- **dappmanager.dnp.dappnode.eth**: 0.2.32, commit: 6e10ba53
- **core.dnp.dappnode.eth**: 0.2.36
- **ipfs.dnp.dappnode.eth**: 0.2.9
- **admin.dnp.dappnode.eth**: 0.2.20, commit: 0cee5543
- **vpn.dnp.dappnode.eth**: 0.2.5
- **bind.dnp.dappnode.eth**: 0.2.4
- **wamp.dnp.dappnode.eth**: 0.2.2
- **wifi.dnp.dappnode.eth**: 0.2.3

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.24.1, build 4667896b
- **Disk usage**: 53%

Error reported in logs:

[session-file-store] Deleting expired sessions
error [ap] Error getting past deposit events FetchError: request to http://prysm-onyx-beacon-chain.dappnode:3000/eth/v1alpha1/node/genesis failed, reason: connect EADDRNOTAVAIL 172.33.0.6:3000 - Local (172.33.0.8:0)
    at ClientRequest. (/app/server/webpack:/node_modules/node-fetch/lib/index.mjs:1449:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[session-file-store] Deleting expired sessions
error [ap] Error getting past deposit events FetchError: request to http://prysm-onyx-beacon-chain.dappnode:3000/eth/v1alpha1/node/genesis failed, reason: connect EADDRNOTAVAIL 172.33.0.6:3000 - Local (172.33.0.8:0)
    at ClientRequest. (/app/server/webpack:/node_modules/node-fetch/lib/index.mjs:1449:11)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by Renaud-V** [comment]
Maybe this is related: in prysm-onyx-validator.dappnode the node stats are stuck (epoch = 39 but should be 319 at time of writing).
![Capture](https://user-images.githubusercontent.com/5773192/84675552-f0f83e80-af1b-11ea-85bb-395bdda149a9.JPG)

**Comment by Renaud-V** [comment]
2 days later, I can confirm the UI of prysm-onyx-validator.dappnode does not show accurate values for "Total balance validating" nor "Node Stats".
![image](https://user-images.githubusercontent.com/5773192/84782043-17c77b00-afd7-11ea-998a-ea99568b7dcf.png)

**Comment by dapplion** [comment]
@Renaud-V I suspect there may be a configuration bug. Can you please go to
UI > packages > Prysm Onyx Validator > config
and change the configuration parameter **from**
```
BEACON_GRPC_GATEWAY_URL: http://prysm-onyx-beacon-chain.dappnode:3000
```
**to**
```
BEACON_GRPC_GATEWAY_URL: http://prysm-onyx-beacon-chain.dappnode:3500
```
Then click update envs and check if the status in the validator is correct
